sudo: false
os:
  - osx
addons:
  apt:
    packages:
      - wkhtmltopdf
before_install:
  - brew update
  - brew install homebrew/boneyard/wkhtmltopdf
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  #- 2.3
  - ruby-head
