sudo: false
os:
  - osx
addons:
  apt:
    packages:
      - wkhtmltopdf
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/boneyard/wkhtmltopdf; fi
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  #- 2.3
  - ruby-head
